### PR TITLE
New Pickup Date Features & Bug Fixes

### PR DESCRIPTION
**Pull request by timnolte**
* Fixes Issues: #15 #16 #17 #18 
* Adds: Pickup time sorting to Dashboard Orders list, Additional order pickup delay times.

### CODE REVIEW

**Comment by timnolte** [comment]
@vyskoczilova can you prepare the Czech translation for this latest version? I'm not sure how you have been building the .po & .mo files but there are Grunt tasks that will do this once you run all of the appropriate development environment commands (composer & npm). You can just run ``grunt makepot`` and once you've finished your translation work you can run grunt po2mo. Once the Czech changes are committed I'll merge the PR to prepare for the final release. Thanks!

**Comment by vyskoczilova** [comment]
@timnolte, I will. I'm not that experience with git, how do I do it properly? Which branch I should download and add another commit? Grunt is not a problem.

**Comment by timnolte** [comment]
@vyskoczilova I'm wondering if it might be easier to manage the translations via @glotpress ? There is an instance already for the plug-in on WordPress.org (https://translate.wordpress.org/projects/wp-plugins/woocommerce-local-pickup-time-select) but I'm also working on setting up our own instance on my website (https://translate.ndigitals.com/glotpress/projects/woocommerce-local-pickup-time-select/). The idea is you can just enter in the translations via a grid form and I can setup the plug-in builds to pull directly from the GlotPress project. This would eliminate any translators from having to get into git/grunt/code/builds/etc. Let me know what you think.

**Comment by vyskoczilova** [comment]
@timnolte Yep, that would be way better - to use WP standard translation, easier to update and everybody could contribute. In that case, publish the new version and when it will be in the repo I will upload the Czech translation in there and ask my colleague to make me an Czech language editor in order to approve the translation.

**Comment by timnolte** [comment]
@vyskoczilova I'll work on getting this workflow setup. I think if we can use my translate.ndigitals.com GlotPress project to start then once this set of changes is published to WordPress.org we can move to using the WordPress hosted GlotPress. Right now the WordPress.org translate site indicates a problem with the plugin, and I know why and it's fixed in my latest PR.

**Comment by timnolte** [comment]
@vyskoczilova if you can go to my site(https://translate.ndigitals.com/glotpress/projects/woocommerce-local-pickup-time-select/) and submit the translations I can then pull the submissions from there. You'll need to login. If you have a WordPress.com account you should be able to login with that, otherwise you'll need to create an account.

**Comment by vyskoczilova** [comment]
@timnolte look's like I can't import the translation already done and I would translate it in PoEdit anyway because it's way quicker. Here you go with updated translations.

[cs_CZ.zip](https://github.com/mattbanks/woocommerce-local-pickup-time/files/2821067/cs_CZ.zip)

**Comment by timnolte** [comment]
@vyskoczilova I did see that you got logged in, I'm wondering though if the import option doesn't show up for non-admin users. I made you a GlotPress admin and a Translation Approver. You should be able to import your .po file under the project options. I'll take of importing what you sent from the attachment. I might need to make some tweaks to the setup. I definitely want to make contributions as easy as possible. Thanks!

**Comment by timnolte** [comment]
@vyskoczilova I just noticed that when you go to the [translation](https://translate.ndigitals.com/glotpress/projects/woocommerce-local-pickup-time-select/cs/default/) at the bottom of the grid there is an [Import Translations](https://translate.ndigitals.com/glotpress/projects/woocommerce-local-pickup-time-select/cs/default/import-translations/) link that should allow you to import. Do you see that option?

**Comment by timnolte** [comment]
@vyskoczilova I got the translation imported but looks like there is 4 items that don't have a translatiions, can you take a look at those? Thanks so much for your work! Now I'm wondering how we can get some more translators? :-)

**Pull request merged**
